#!/bin/sh -e

        
# remove wrong subdir /usr/share/mxflux/menu/out-of-sight

if [ -e   /usr/share/mxflux/menu/out-of-sight/out-of-sight ]; then
    mv    /usr/share/mxflux/menu/out-of-sight /usr/share/mxflux/menu/out-of-sight.moved  || :
    mv    /usr/share/mxflux/menu/out-of-sight.moved/out-of-sight /usr/share/mxflux/menu/out-of-sight  || :
    rmdir /usr/share/mxflux/menu/out-of-sight.moved || :
fi


