#!/bin/sh -e

        
# remove wrong subdir /usr/share/mxflux/menu/out-of-sight

if [ -e   /usr/share/mxflux/menu/out-of-sight/out-of-sight ]; then
    mv    /usr/share/mxflux/menu/out-of-sight /usr/share/mxflux/menu/out-of-sight.moved  || :
    mv    /usr/share/mxflux/menu/out-of-sight.moved/out-of-sight /usr/share/mxflux/menu/out-of-sight  || :
    rmdir /usr/share/mxflux/menu/out-of-sight.moved || :
fi

# remove incorrect /etc/X11/Xsession.d/21fluxbox-defaults-mx folder

if [ -d /etc/X11/Xsession.d/21fluxbox-defaults-mx ]; then
	rm -r /etc/X11/Xsession.d/21fluxbox-defaults-mx
fi


